# Generated by Django 4.1 on 2022-08-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brdapp', '0002_author_category_post_postcategory_post_postcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tank', 'Танки'), ('heal', 'Хилы'), ('dd', 'ДД'), ('buyers', 'Торговцы'), ('guildmaster', 'Гилдмастеры'), ('quest', 'Квестгиверы'), ('smith', 'Кузнецы'), ('tanner', 'Кожевники'), ('potion', 'Зельевары'), ('spellmaster', 'Мастера заклинаний')], default='tank', max_length=64),
        ),
    ]
