# Generated by Django 4.1 on 2022-08-25 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brdapp', '0005_alter_userresponse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='create',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
    ]
